TRAD804 update to latest proto
bloXroute-Labs/solana-trader-client-go pull request #137
Opened 2023-07-26 15:03 UTC by atulsriv

2023-07-26 16:26 UTC, kdonthi approved these changes

2023-08-08 17:07 UTC, DimaCantemir requested changes

2023-08-08 17:07 UTC, DimaCantemir commented on provider/common.go
> +	case pb.Side_S_UNKNOWN:
you are still using protobuf enums. The point of this was to phase PB enums out from everywhere not only in the communication layer.

2023-08-08 17:07 UTC, DimaCantemir commented on provider/common.go
> +		return "validation-error"
by validation error I meant trader api was supposed to return a validation error from the endpoint if Side's value was different then the 2 supported values

2023-08-08 17:07 UTC, DimaCantemir commented on provider/common.go
> +func convertOrderTypeToString(orderType common.OrderType) string {
same as above, you convert from enum to strings but we are trying to get rid of the enums from our code. just use strings, define them as constants

2023-08-08 17:07 UTC, DimaCantemir commented on provider/grpc.go
> +func (g *GRPCClient) PostOrderV2(ctx context.Context, owner, payer, market string, side pb.Side, orderType common.OrderType, amount, price float64, opts PostOrderOpts) (*pb.PostOrderResponse, error)
change "side" and "type" here to be string. And do this everywhere

2023-08-08 19:50 UTC, DimaCantemir approved these changes

2023-08-08 19:50 UTC, merged