Adding postSubmitV2
bloXroute-Labs/solana-trader-client-go pull request #143
Opened 2023-11-28 22:52 UTC by tinystarinagalaxy

2023-11-29 15:33 UTC, DimaCantemir requested changes

2023-11-29 15:33 UTC, DimaCantemir commented on provider/grpc.go
> +	return g.apiClient.PostSubmitBatch(ctx, request)
PostSubmitBatch -> PostSubmitBatchV2

2023-12-13 15:35 UTC, tinystarinagalaxy commented on provider/grpc.go
> +	return g.apiClient.PostSubmitBatch(ctx, request)
done

2023-12-13 18:04 UTC, DimaCantemir approved these changes

2023-12-13 18:04 UTC, merged