Add Jito bundling support
bloXroute-Labs/solana-trader-client-go pull request #155
Opened 2024-01-29 19:13 UTC by atulsriv

- Add helper utils for creating tip instruction
- Add helper utils for creating tip transaction
- Add support in providers to support modified endpoints
-

2024-02-05 17:52 UTC, DimaCantemir requested changes
please cleanup and make consistent changes across all providers

2024-02-05 17:52 UTC, DimaCantemir commented on provider/ws.go
> +// PostSubmitJitoBundle takes in a list of transactions, signs them, and submits them to PostSubmitJitoEndpoint
either uncomment or remove

2024-02-05 17:52 UTC, DimaCantemir commented on provider/http.go
> +	frontRunningProtection := true
Why is the hardcoded ?

2024-02-06 17:55 UTC, atulsriv commented on provider/http.go
> +	frontRunningProtection := true
removed

2024-02-06 23:47 UTC, DimaCantemir approved these changes

2024-02-06 23:47 UTC, DimaCantemir commented on provider/ws.go
> +	txBase64, err := transaction.SignTxWithPrivateKey(txBase64, *w.privateKey)
why don't we have this in the other providers ?

2024-02-13 18:17 UTC, DimaCantemir approved these changes

2024-02-13 18:17 UTC, merged