BX-4015 Work on Orderbook SDK
bloXroute-Labs/solana-trader-client-go pull request #2
Opened 2022-04-08 03:19 UTC by kdonthi

* Creating GetOrderbook and GetOrderbookStream for clients to use in library

2022-04-08 23:51 UTC, kdonthi commented on bxserum/provider/ws.go
> +				response, err := recvWSResponse[T](conn)
I can put this inside a go routine and get the result from a channel, but thought it was unnecessary

2022-04-08 23:56 UTC, kdonthi commented on bxserum/provider/ws.go
> +func unaryWSRequest[T any](conn *websocket.Conn, request string) (*T, error) {
We can create two type sets of the stream and non-stream responses to restrict what types can be passed in

2022-04-09 03:34 UTC, kdonthi commented on bxserum/helpers/ws.go
> +func UnaryWSRequest[T any](conn *websocket.Conn, request string) (*T, error) {
Create type sets for allowed types?

2022-04-11 18:28 UTC, aspin requested changes
Generally looks good! I'd suggest fixing the `json.RawMessage` thing now and making a follow up ticket for message separation

2022-04-11 18:28 UTC, aspin commented on bxserum/provider/ws.go
> +func (w *WSClient) CloseConn() error {
`Close()` is enough

2022-04-11 18:28 UTC, aspin commented on cmd/wsclient/main.go
> +	w, err := provider.NewWSClient("ws://174.129.154.164:1810/ws")
It'd probably be a good idea for the default client to have our address hardcoded, e.g.

```
provider.NewWSClient() // connects to production
provider.NewWSClientTestnet() // doesn't exist yet
provider.NewWSClientWithEndpoint("") // if you want to manually specify
```

2022-04-11 18:28 UTC, aspin commented on cmd/wsclient/main.go
> +	orderBook, err := w.GetOrderbook("ETH/USDT")
minor: orderbook as one word

2022-04-11 18:28 UTC, aspin commented on bxserum/provider/ws.go
> +	request := fmt.Sprintf(`{"jsonrpc": "2.0", "id": 1, "method": "GetOrderbookStream", "params": {"market":"%s"}}`, market)
it'd probably be a good idea to write some methods around this to construct the `jsonrpc2` object instead of writing the string directly

2022-04-11 18:28 UTC, aspin commented on bxserum/helpers/ws.go
> +	return recvWSResult[T](conn)
One problem you're going to experience right now is that you're going to have issues interweaving unary requests and streams. I think this is fine as a v0.1, but you may find that your requests get intercepted between each other. To solve this you're going to need to create a single go routine that dispatches all read messages to either a waiting request handler or subscribed stream. I think let's not solve this right away but create a ticket and add a big fat TODO on this file for that. I have the same issue in Python right now: https://bloxroute.atlassian.net/browse/BX-4123

2022-04-11 18:28 UTC, aspin commented on bxserum/helpers/ws.go
> +			case <-ctx.Done():
this is nice :+1:

2022-04-11 18:28 UTC, aspin commented on bxserum/helpers/ws.go
> +	resultBytes, err := resp.Result.MarshalJSON()
I'd like to avoid this if possible. What type does `jsonrpc2.Response` deserialize to? We're probably going to want it to be `json.RawMessage`, which will skip any deserialization, and then you can call `Unmarshal` on it again.

2022-04-11 18:28 UTC, aspin commented on bxserum/helpers/ws.go
> +package helpers
I think I would want the contents of this file being in `ws.go`, or a closely related file like `provider/ws_conn.go`. I'm not sure yet, but I don't want a `helpers` module to grow too large

2022-04-11 22:40 UTC, kdonthi commented on bxserum/helpers/ws.go
> +	return recvWSResult[T](conn)
Sounds good and I added a TODO.

I think that having unique request IDs for each request is important for that, so I went ahead and created a function to get/increment the request ID for each request using a lock.

2022-04-11 22:54 UTC, kdonthi commented on bxserum/helpers/ws.go
> +	resultBytes, err := resp.Result.MarshalJSON()
If I understand your question, the `jsonrpc2.Response` is a struct that has fields for the ID, Result, and Error. The issue with replacing it with `json.RawMessage` is that I will not be able to separate the Result field as easily from it. When I tried replacing the struct, I got empty values in the response structs.

2022-04-11 23:04 UTC, kdonthi commented on bxserum/helpers/ws.go
> +package helpers
Do you mean I should keep it in one of those places or I shouldn't? I can also rename the folder to `requests` if that helps?

2022-04-11 23:05 UTC, kdonthi commented on bxserum/helpers/ws.go
> +			case <-ctx.Done():
:)

2022-04-11 23:33 UTC, kdonthi commented on bxserum/helpers/ws.go
> +	resultBytes, err := resp.Result.MarshalJSON()
One thing I tried to do was to create an in function struct like this:
```
type response struct {
    Response T
}
```
but I got the error that `type declarations inside generic functions are not currently supported`

2022-04-12 00:24 UTC, aspin commented on bxserum/helpers/ws.go
> +	resultBytes, err := resp.Result.MarshalJSON()
Yeah sorry what I want is only the `Result` field to be `json.RawMessage`.

So something like

```go
type response struct {
    ID string
    Result json.RawMessage
    Error error
}

// later

json.Unmarshal(response.Result, &impl)
```

which delay deserializing the `Result` field specifically

2022-04-12 00:31 UTC, aspin commented on bxserum/helpers/ws.go
> +package helpers
Fixed the comment –– sorry I didn't type that out well. Basically, the logic in here isn't really related to each other, and as it grows will end up wanting to be three different packages, I think (`http`, `ws` and `grpc`). We can hold off on refactoring that until later though.

2022-04-12 00:38 UTC, aspin reviewed
`provider/ws.go` looks :+1:

2022-04-12 00:38 UTC, aspin commented on bxserum/helpers/ws.go
> +func GetRequestID() uint64 {
`RequestID()` (no Get)

2022-04-12 00:38 UTC, aspin commented on bxserum/helpers/ws.go
> +func UnaryWSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
Do you like `Unary` in the name of this function? I honestly don't really know why GRPC calls these functions `unaryUnary` and `unaryStream`. I think it might be nicer if we separated all these into `ws`, `http`, and `grpc`, then just called this `Request` and `Stream`. So the usage would be `ws.Request` and `ws.Stream`. 

Alternatively, since we might need some struct eventually to track each of the different ws streams, we might want to define an interface for each of the types with `Request` and `Stream` methods respectively. wdyt?

2022-04-12 00:38 UTC, aspin commented on bxserum/helpers/ws.go
> +func UnaryWSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
in the second case I'd suggest the module be `connections`?

2022-04-12 01:08 UTC, kdonthi commented on bxserum/helpers/ws.go
> +	resultBytes, err := resp.Result.MarshalJSON()
Got it, I believe the jsonrpc2.Response has a `json.RawMessage` for its Result.
```
type Response struct {
    ID     ID               `json:"id"`
    Result *json.RawMessage `json:"result,omitempty"`
    Error  *Error           `json:"error,omitempty"`
    Meta   *json.RawMessage `json:"meta,omitempty"`
}
```

But I think I will create a new struct like you suggested; dereferencing a pointer to a RawMessage makes me uneasy.

2022-04-12 01:58 UTC, kdonthi commented on bxserum/helpers/ws.go
> +func UnaryWSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
I wanted to use Unary to be consistent with the Python SDK, but I think removing it will be better for naming. I also like the name `connections` for the package name.

An interface and different structs would be nice, but currently methods cannot have type parameters. Maybe, we can keep track of the streams inside the client structs (i.e. WSClient)?

2022-04-12 16:13 UTC, aspin requested changes
just a couple more

2022-04-12 16:13 UTC, aspin commented on bxserum/connections/ws.go
> +func WSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
The main concern I expect to have about all of this eventually is that the state is all global. I really like having the generic `recWSResult[T]` function, but I don't want the final state of this to have a global channel for processing all websocket messages. It should be possible for the user to create multiple websocket clients and have them all be dependent on each other. But I think fine for this PR for now.

2022-04-12 16:13 UTC, aspin commented on bxserum/connections/ws.go
> +func RequestID() uint64 {
thought about this some more and I don't think this should be global either. Probably should just be an attribute on the websocket provider (or if you want it to be its own stryct with only a `Next()` function that would be a good candidate for a `utils` type package). Should probably also simplify this function just a little bit and use `defer`

```go
requestIDLock.Lock()
defer requestIDLock.Unlock()

val := requestID
requestID++
return val
```

2022-04-12 18:49 UTC, kdonthi commented on bxserum/connections/ws.go
> +func WSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
Did you mean dependent or independent?

2022-04-12 18:58 UTC, aspin commented on bxserum/connections/ws.go
> +func WSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
independent** my bad

2022-04-12 19:00 UTC, aspin commented on utils/request_id.go
> +func (r RequestID) Next() uint64 {
this needs a pointer receiver I think

2022-04-12 19:00 UTC, aspin commented on bxserum/connections/ws.go
> +func RequestID() uint64 {
remove this code now?

2022-04-12 19:44 UTC, kdonthi commented on bxserum/connections/ws.go
> +func WSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
I think that since we have a different connection for each client, that should be fine?

2022-04-12 19:49 UTC, aspin commented on bxserum/connections/ws.go
> +func WSRequest[T any](conn *websocket.Conn, request []byte) (*T, error) {
well where do you envision the global channel for handling all subscription messages to live? The code as is it currently is doesn't allocated this global channel for each connection. You'd have to pass it in on each function call and that's a bit clunky to pass in both a global channel and a channel for subscription events (for example)

2022-04-12 19:49 UTC, aspin approved these changes

2022-04-12 20:05 UTC, merged