BX-4015 HTTP/GRPC Support
bloXroute-Labs/solana-trader-client-go pull request #3
Opened 2022-04-13 04:57 UTC by kdonthi

* Create README to give an overview and show usages
* Support and client samples for HTTP and GRPC clients
* Cleaning up WS client sample for consistency

2022-04-13 22:48 UTC, kdonthi commented on bxserum/provider/grpc.go
> +	go streamResponse[pb.GetOrderbookStreamResponse](stream, market, outputChan)
space

2022-04-13 22:48 UTC, kdonthi commented on bxserum/provider/grpc.go
> +		err := stream.RecvMsg(output)
space

2022-04-13 22:50 UTC, kdonthi commented on cmd/grpcclient/main.go
> +		log.Errorf("error dialing GRPC client - %v", err)
return

2022-04-13 22:50 UTC, kdonthi commented on cmd/grpcclient/main.go
> +		log.Errorf("error dialing GRPC client - %v", err)
return

2022-04-13 22:50 UTC, kdonthi commented on cmd/grpcclient/main.go
> +		log.Errorf("error with GetOrderbook request for SOL-USDT - %v", err)
fix error msg

2022-04-13 22:59 UTC, kdonthi commented on README.md
> +in Go. As we continue to develop the Serum API, we will update this code to have more methods as well. Currently the methods supported are:
the methods here

2022-04-14 02:49 UTC, kdonthi commented on README.md
> +    g, err := provider.NewGRPCClient() // you can replace this with `NewWSClient()` to use WebSockets
```suggestion
    g, err := provider.NewGRPCClient() // replace this with `NewWSClient()` to use WebSockets
```

2022-04-14 02:54 UTC, kdonthi commented on bxserum/provider/grpc.go
> +func NewGRPCClientWithEndpoint(baseURL string) (*GRPCClient, error) {
endpoint

2022-04-14 02:56 UTC, kdonthi commented on bxserum/provider/grpc.go
> +	go streamResponse[pb.GetOrderbookStreamResponse](stream, market, outputChan)
pass in pointer to stream?

2022-04-14 02:56 UTC, kdonthi commented on bxserum/provider/http.go
> +func NewHTTPClientWithEndpoint(baseURL string) *HTTPClient {
endpoint

2022-04-14 02:58 UTC, kdonthi commented on cmd/grpcclient/main.go
> +	// Stream response
move this down

2022-04-15 16:38 UTC, aspin requested changes
minor comments

2022-04-15 16:38 UTC, aspin commented on README.md
> +This SDK is designed to make it easy for you to use the [Bloxroute Labs Serum API](https://github.com/bloXroute-Labs/serum-api)
Bloxroute => bloXroute

2022-04-15 16:38 UTC, aspin commented on README.md
> +```azure
minor: guessing Goland autofilled in `azure` for you? prob should take it out

2022-04-15 16:38 UTC, aspin commented on README.md
> +To run some working code samples, please visit the `cmd` directory where you can see examples of code for each client.
I think it's common to name this `examples/`? not sure for Go libraries

2022-04-15 16:38 UTC, aspin commented on bxserum/connections/http.go
> +func HTTPGetResponse[T any](client *http.Client, url string) (*T, error) {
`HTTPGet` is enough

2022-04-15 16:38 UTC, aspin commented on bxserum/connections/http.go
> +	if client == nil {
It'd be probably be good to make two functions: `HTTPGet` and `HTTPGetWithClient` and give the caller the default http client

2022-04-15 16:38 UTC, aspin commented on bxserum/connections/http.go
> +	if client == nil {
I think usually you also return an `error` for this kind of `nil` pointer problem –– you'll usually just let the code panic so the developer who made this mistake gets alerted since it's not really part of normal operation.

2022-04-15 16:38 UTC, aspin commented on bxserum/connections/http.go
> +func httpUnmarshalResponse[T any](httpResp *http.Response) (*T, error) {
probably can omit `Response` from the function name here too

2022-04-15 16:38 UTC, aspin commented on bxserum/provider/http.go
> +func NewHTTPClientWithEndpoint(endpoint string) *HTTPClient {
can probably create just one constructor that allows the user to pass in both the endpoint and the httpClient so they can configure it to their satisfaction

2022-04-15 16:38 UTC, aspin commented on bxserum/provider/http.go
> +	return &HTTPClient{baseURL: endpoint, httpClient: &client} // TODO handle possible forward slash at end of base url?
i'd suggest not worrying about that validation

2022-04-15 21:56 UTC, kdonthi commented on bxserum/connections/http.go
> +	if client == nil {
For the second point, should we only panic when it is the developer's fault?

I.e. Should we return an error if the HTTP response from the client is nil? Yes, I think?

2022-04-15 21:58 UTC, aspin commented on bxserum/connections/http.go
> +	if client == nil {
yes, panic is usually for when it's the developer fault or some irrecoverable invariant has been broken (i.e. user error in startup arguments). In your example, a server returning an empty response is usually not the developer or user's fault.

2022-04-18 18:18 UTC, aspin approved these changes

2022-04-18 20:08 UTC, merged