[BX-4142] Add mapping for ws requests.
bloXroute-Labs/solana-trader-client-go pull request #6
Opened 2022-05-09 18:41 UTC by Jeeyb

2022-05-10 17:09 UTC, aspin commented on bxserum/provider/ws.go
> +	r.Mutex.Lock()
since your embedding the mutex in `r`, you can just do `r.Lock()`

2022-05-10 17:09 UTC, aspin commented on bxserum/provider/ws.go
> +		log.Println(response)
delete this line?

2022-05-10 17:09 UTC, aspin commented on bxserum/provider/ws.go
> +	return connections.WSRequest[pb.GetOrderbookResponse](w.conn, request, responseChan)
This sequence of calls looks like it can be refactored into a single function?

2022-05-10 17:09 UTC, aspin commented on bxserum/provider/ws.go
> +	return connections.WSRequest[pb.GetOrderbookResponse](w.conn, request, responseChan)
I'm not sure it makes sense to keep `connections/ws.go` in general –– it might be better to move most of that logic into this struct. It's just a bit weird to call a function `WSRequest`, then give that function the response channel to which the calling code intends to write the response to. From the signature of the `WSRequest` `responseChan` looks like it should be getting the response written to it –– something like

```go
connections.WSRequest[pb.GetOrderbookResponse](w.conn, request, responseCh)
<-responseCh
```

2022-05-10 17:09 UTC, aspin commented on bxserum/provider/ws.go
> +	return connections.WSRequest[pb.GetOrderbookResponse](w.conn, request, responseChan)
I would also consider writing a wrapper struct in `connections/ws.go` and leaving `provider/ws.go` completely unaware of the mechanics behind request IDs / subscription IDs. Something like

```go
type WsRPC interface {
    Request(methodName string, message json.RawMessage) (json.RawMessage, error)
    Stream(message json.RawMessage, responses chan json.RawMessage) error // provider/ws.go doesn't really need to know about subscription IDs
}

func (w *wsRPC) read() { ... }

func (w *wsRPC) Request(methodName string, message []byte) json.RawMessage {
    id := w.nextID()
    rpcMessage := jsonrpc2.Request { ID: id, Method: methodName, Params: message }
    w.conn.Send(rpcMessage)
    
    response, err := w.wait(id)
    return response.Result, err
}

// provider/ws.go
func (w *WSClient) GetOrderbook(market string, limit uint32) (*pb.GetOrderbookResponse, error) {
    params := map[string]interface{}{"market": market, "limit": limit})

    result, err := w.wsRPC.Request("GetOrderbook", params)
    if err != nil {
        return nil, err
    }

    var response pb.GetOrderbookResponse
     json.Unmarshal(...)
}
```

2022-05-16 15:32 UTC, Jeeyb commented on bxserum/connections/ws.go
> +	go wsRPC.read()
Probably we need send message to customer if something went wrong, mb add something like error chan ? @aspin WDYT?

2022-05-20 17:18 UTC, aspin requested changes

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +	r.Mutex.Lock()
`r.Lock()` `defer r.UnLock()`. Though I don't think you really want to make `r.Mutex` visible outside of this struct? IMO should be a private property `m` or something

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +	dataReceivers map[uint64]chan json.RawMessage
naming suggestion: `dataReceiver` sounds like you can receive data on these channels. Suggest something like `requestListeners` or `requestWaiters`

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +	nonStreamRequests   requests
ok to just call this `requests`: request already implies not a stream

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +		s.subscriptions[response.Result] = s.dataReceivers[response.ID]
I think this is a possible race condition? What if `delete` is called at the same time as this line? I think it should be possible to code this all out without any mutexs if you're just using a single loop to do all the reading/writing

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +			return errors.New("failed to check ")
fill this out? would be a malformed error –– could probably just serialize the whole thing an include it

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +		if resp.ID.Str == "null" {
This isn't a good guarantee –– the initial subscription response with the subscription ID can have a response ID. It's the subsequent responses that don't have a request ID.

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +		responseReader, ok := w.nonStreamRequests.dataReceivers[resp.ID.Num]
I think you should probably do this part before trying to unmarshall the subscription format

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +	go wsRPC.read()
Yeah, I think so. But a dedicated error channel would be clumsy to work with, wouldn't it? Should probably make all the `chan json.RawMessage` types instead be a struct like this 

```
type RPCResponse {
    result *json.RawMessage
    err error
}
```

Then in the request side you could check each of  these fields to see which one is set?

2022-05-20 17:18 UTC, aspin commented on bxserum/connections/ws.go
> +		s.subscriptions[response.Result] = s.dataReceivers[response.ID]
It's a little bit confusing that the receiving channel is moved from `s.request` to `s.subscriptions`. Add a comment to clarify what's happening.

2022-05-24 20:12 UTC, Jeeyb commented on bxserum/connections/ws.go
> +		if resp.ID.Str == "null" {
null means that we already have subscription ID

2022-06-21 20:46 UTC, aspin commented
continuing in other ticket

2022-06-21 20:46 UTC, closed without merging